// cars-data.js – Complete data for all 10 requested cars
const carDatabase = [
    {
        make: "Leapmotor", model: "C10", trim: "Design", year: 2025, bodyStyle: "Mid-size SUV", driveType: "RWD",
        engineType: "Electric", displacement: "N/A", cylinders: "N/A", valvetrain: "N/A", aspiration: "N/A",
        horsepower: "218 hp", torque: "258 lb-ft", redline: "N/A", fuelType: "EV", batteryCapacity: "69.9 kWh",
        electricMotorPower: "160 kW", combinedSystemPower: "160 kW", transmission: "Single-speed",
        zeroToHundred: "7.5 s", topSpeed: "170 km/h", fuelEconomy: "19,9 kWh/100km", range: "424 km",
        length: "4739 mm", width: "1900 mm", height: "1680 mm", wheelbase: "2825 mm",
        trackFront: "1640 mm", trackRear: "1645 mm", groundClearance: "180 mm", curbWeight: "1980 kg",
        gvwr: "2450 kg", towingCapacity: "1600 kg", payloadCapacity: "470 kg",
        frontSuspension: "MacPherson", rearSuspension: "Multi-link", steeringType: "Rack-and-pinion",
        turningCircle: "11.5 m", brakeType: "Disc/disc", wheelSize: "20\"", tireSize: "245/45R20",
        headroomFront: "1020 mm", headroomRear: "980 mm", legroomFront: "1050 mm", legroomRear: "950 mm",
        shoulderFront: "1450 mm", shoulderRear: "1400 mm", hipFront: "1380 mm", hipRear: "1330 mm",
        passengerVolume: "3.2 m³", seatingCapacity: 5, cargoVolume: "435 L", cargoFolded: "1410 L",
        trunkOpeningWidth: "1050 mm", trunkOpeningHeight: "850 mm", liftoverHeight: "700 mm",
        fuelTank: "N/A", estimatedRange: "437 km", crashTestRatings: "5 stars", standardSafety: "6 airbags, AEB, ESC",
        availableADAS: "Adaptive Cruise, Lane Keep, 360° Camera", screenSize: "14.6\"", appleCarPlay: "Yes",
        androidAuto: "Yes", audioSystem: "12 speakers", usbPorts: "6", num12VOutlets: "2", wirelessCharging: "Yes",
        seatMaterial: "Leatherette", powerSeats: "Driver/Passenger", heatedSeats: "Front", ventilatedSeats: "Front",
        dualZoneClimate: "Yes", panoramicSunroof: "Yes", keylessEntry: "Yes", handsFreeLiftgate: "Yes",
        basePrice: "33 490 €", img: "https://www.leapmotor.sk/wp-content/uploads/2025/03/leapmotor-c10.jpg",
        buyingLink: "https://www.leapmotor.sk/c10"
    },
    {
        make: "Leapmotor", model: "B10", trim: "Design Max", year: 2025, bodyStyle: "Compact SUV", driveType: "RWD",
        engineType: "Electric", displacement: "N/A", cylinders: "N/A", valvetrain: "N/A", aspiration: "N/A",
        horsepower: "217 hp", torque: "240 Nm", redline: "N/A", fuelType: "EV", batteryCapacity: "67.1 kWh",
        electricMotorPower: "160 kW", combinedSystemPower: "160 kW", transmission: "Single-speed",
        zeroToHundred: "6.8 s", topSpeed: "170 km/h", fuelEconomy: "17.3 kWh/100km", range: "510 km",
        length: "4515 mm", width: "1885 mm", height: "1655 mm", wheelbase: "2735 mm",
        trackFront: "1580 mm", trackRear: "1585 mm", groundClearance: "170 mm", curbWeight: "1750 kg",
        gvwr: "2200 kg", towingCapacity: "1500 kg", payloadCapacity: "450 kg",
        frontSuspension: "MacPherson", rearSuspension: "Torsion beam", steeringType: "Rack-and-pinion",
        turningCircle: "11.0 m", brakeType: "Disc/disc", wheelSize: "18\"", tireSize: "215/60R18",
        headroomFront: "1010 mm", headroomRear: "980 mm", legroomFront: "1040 mm", legroomRear: "940 mm",
        shoulderFront: "1420 mm", shoulderRear: "1370 mm", hipFront: "1360 mm", hipRear: "1310 mm",
        passengerVolume: "2.9 m³", seatingCapacity: 5, cargoVolume: "420 + 95 L", cargoFolded: "1200 L",
        trunkOpeningWidth: "1000 mm", trunkOpeningHeight: "750 mm", liftoverHeight: "680 mm",
        fuelTank: "N/A", estimatedRange: "510 km", crashTestRatings: "4 stars", standardSafety: "6 airbags, AEB",
        availableADAS: "Adaptive Cruise, Lane Keep", screenSize: "12.8\"", appleCarPlay: "Yes", androidAuto: "Yes",
        audioSystem: "8 speakers", usbPorts: "4", num12VOutlets: "2", wirelessCharging: "Yes", seatMaterial: "Cloth",
        powerSeats: "Driver", heatedSeats: "Front", ventilatedSeats: "N/A", dualZoneClimate: "Yes",
        panoramicSunroof: "Yes", keylessEntry: "Yes", handsFreeLiftgate: "Optional",
        basePrice: "28 990 €", img: "https://www.leapmotor.sk/wp-content/uploads/2025/02/leapmotor-b10.jpg",
        buyingLink: "https://www.leapmotor.sk/b10"
    },
    {
        make: "Peugeot", model: "308 Hatchback", trim: "Allure", year: 2018, bodyStyle: "Hatchback", driveType: "FWD",
        engineType: "Inline-4", displacement: "1.6L", cylinders: 4, valvetrain: "DOHC", aspiration: "Turbo",
        horsepower: "120 hp", torque: "221 lb-ft", redline: "4000 rpm", fuelType: "Diesel",
        batteryCapacity: "N/A", electricMotorPower: "N/A", combinedSystemPower: "88 kW",
        transmission: "6-speed manual", zeroToHundred: "9.6 s", topSpeed: "210 km/h",
        fuelEconomy: "5.7 L/100km", range: "1262 km", length: "4253 mm", width: "1804 mm", height: "1457 mm",
        wheelbase: "2738 mm", trackFront: "1553 mm", trackRear: "1560 mm", groundClearance: "140 mm",
        curbWeight: "1265 kg", gvwr: "1775 kg", towingCapacity: "1300 kg", payloadCapacity: "510 kg",
        frontSuspension: "MacPherson", rearSuspension: "Torsion beam", steeringType: "Rack-and-pinion",
        turningCircle: "10.8 m", brakeType: "Disc/disc", wheelSize: "16\"", tireSize: "205/60R16",
        headroomFront: "1020 mm", headroomRear: "970 mm", legroomFront: "1070 mm", legroomRear: "910 mm",
        shoulderFront: "1390 mm", shoulderRear: "1340 mm", hipFront: "1370 mm", hipRear: "1320 mm",
        passengerVolume: "2.8 m³", seatingCapacity: 5, cargoVolume: "420 L", cargoFolded: "1300 L",
        trunkOpeningWidth: "950 mm", trunkOpeningHeight: "700 mm", liftoverHeight: "650 mm",
        fuelTank: "53 L", estimatedRange: "1262 km", crashTestRatings: "5 stars", standardSafety: "6 airbags, AEB",
        availableADAS: "Active Safety Brake", screenSize: "9.7\"", appleCarPlay: "Yes", androidAuto: "Yes",
        audioSystem: "6 speakers", usbPorts: "2", num12VOutlets: "2", wirelessCharging: "N/A",
        seatMaterial: "Cloth", powerSeats: "N/A", heatedSeats: "Front", ventilatedSeats: "N/A",
        dualZoneClimate: "Yes", panoramicSunroof: "Optional", keylessEntry: "Optional", handsFreeLiftgate: "N/A",
        basePrice: "8 990 €", img: "https://upload.wikimedia.org/wikipedia/commons/7/7e/2018_Peugeot_308_Allure_BlueHDi_FACELIFT.jpg",
        buyingLink: "https://peugeot-308.autobazar.sk/"
    },
    {
        make: "Volkswagen", model: "ID.4", trim: "Pro Performance", year: 2022, bodyStyle: "SUV", driveType: "RWD",
        engineType: "Electric", displacement: "N/A", cylinders: "N/A", valvetrain: "N/A", aspiration: "N/A",
        horsepower: "204 hp", torque: "229 lb-ft", redline: "N/A", fuelType: "EV", batteryCapacity: "77 kWh",
        electricMotorPower: "150 kW", combinedSystemPower: "150 kW", transmission: "Single-speed",
        zeroToHundred: "8.5 s", topSpeed: "99 mph", fuelEconomy: "17.7 kWh/100km", range: "531 km",
        length: "4584 mm", width: "1852 mm", height: "1638 mm", wheelbase: "2769 mm",
        trackFront: "1587 mm", trackRear: "1584 mm", groundClearance: "210 mm", curbWeight: "2140 kg",
        gvwr: "2720 kg", towingCapacity: "1000 kg", payloadCapacity: "580 kg",
        frontSuspension: "MacPherson", rearSuspension: "Multi-link", steeringType: "Rack-and-pinion",
        turningCircle: "11.9 m", brakeType: "Disc/disc", wheelSize: "19\"", tireSize: "235/50R19",
        headroomFront: "1034 mm", headroomRear: "991 mm", legroomFront: "1041 mm", legroomRear: "965 mm",
        shoulderFront: "1460 mm", shoulderRear: "1421 mm", hipFront: "1394 mm", hipRear: "1357 mm",
        passengerVolume: "3.0 m³", seatingCapacity: 5, cargoVolume: "543 L", cargoFolded: "1575 L",
        trunkOpeningWidth: "1000 mm", trunkOpeningHeight: "800 mm", liftoverHeight: "720 mm",
        fuelTank: "N/A", estimatedRange: "531 km", crashTestRatings: "5 stars", standardSafety: "7 airbags, AEB",
        availableADAS: "IQ.DRIVE, Travel Assist", screenSize: "12\"", appleCarPlay: "Yes", androidAuto: "Yes",
        audioSystem: "7 speakers", usbPorts: "4", num12VOutlets: "2", wirelessCharging: "Optional",
        seatMaterial: "Cloth", powerSeats: "Driver", heatedSeats: "Front", ventilatedSeats: "N/A",
        dualZoneClimate: "Yes", panoramicSunroof: "Optional", keylessEntry: "Yes", handsFreeLiftgate: "Optional",
        basePrice: "38 990 €", img: "https://www.vw.sk/content/dam/vwng/vwpkw/id4/models/2022/id4-pro-performance-max.jpg",
        buyingLink: "https://www.vw.sk/id4"
    },
    {
        {
    make: "KGM",
    model: "Torres",
    trim: "EVX",
    year: 2025,
    bodyStyle: "Mid-size SUV",
    driveType: "FWD",
    engineType: "Electric",
    displacement: "N/A",
    cylinders: "N/A",
    valvetrain: "N/A",
    aspiration: "N/A",
    horsepower: "207 hp",
    torque: "339 Nm",
    redline: "N/A",
    fuelType: "EV",
    batteryCapacity: "73.4 kWh",
    electricMotorPower: "152.2 kW",
    combinedSystemPower: "152.2 kW",
    transmission: "Single-speed",
    zeroToHundred: "8.1 s",
    topSpeed: "175 km/h",
    fuelEconomy: "18.7 kWh/100 km",
    range: "462 km (WLTP)",
    length: "4715 mm",
    width: "1890 mm",
    height: "1715 mm",
    wheelbase: "2680 mm",
    trackFront: "1620 mm",
    trackRear: "1640 mm",
    groundClearance: "169 mm",
    curbWeight: "1915 kg",
    gvwr: "2410 kg",
    towingCapacity: "1500 kg",
    payloadCapacity: "495 kg",
    frontSuspension: "MacPherson",
    rearSuspension: "Multi-link",
    steeringType: "Rack-and-pinion",
    turningCircle: "10.8 m",
    brakeType: "Disc/disc",
    wheelSize: "18\" / 20\"",
    tireSize: "225/60R18 or 245/45R20",
    headroomFront: "N/A",
    headroomRear: "N/A",
    legroomFront: "N/A",
    legroomRear: "N/A",
    shoulderFront: "N/A",
    shoulderRear: "N/A",
    hipFront: "N/A",
    hipRear: "N/A",
    passengerVolume: "N/A",
    seatingCapacity: 5,
    cargoVolume: "703 L (min) / 1662 L (max)",
    cargoFolded: "1662 L",
    trunkOpeningWidth: "N/A",
    trunkOpeningHeight: "N/A",
    liftoverHeight: "N/A",
    fuelTank: "N/A",
    estimatedRange: "462 km",
    crashTestRatings: "N/A",
    standardSafety: "Driver/Passenger airbags & basic safety suite (varies by market)",
    availableADAS: "Optional ADAS packages available",
    screenSize: "12.3\" (dual displays)",
    appleCarPlay: "Yes",
    androidAuto: "Yes",
    audioSystem: "N/A",
    usbPorts: "N/A",
    num12VOutlets: "N/A",
    wirelessCharging: "Yes",
    seatMaterial: "Varies by trim",
    powerSeats: "Yes (trim dependent)",
    heatedSeats: "Yes",
    ventilatedSeats: "Optional",
    dualZoneClimate: "Yes",
    panoramicSunroof: "Optional",
    keylessEntry: "Yes",
    handsFreeLiftgate: "Yes",
    basePrice: "Varies by market",
    img: "N/A",
    buyingLink: "N/A"
},
    {
        make: "Dacia", model: "Bigster Hybrid 155", trim: "Expression", year: 2025, bodyStyle: "SUV", driveType: "FWD",
        engineType: "1.8L + Electric", displacement: "1.8L", cylinders: 4, valvetrain: "DOHC", aspiration: "N/A",
        horsepower: "155 hp", torque: "205 Nm", redline: "N/A", fuelType: "Hybrid", batteryCapacity: "1.4 kWh",
        electricMotorPower: "67 hp", combinedSystemPower: "155 hp", transmission: "6-speed auto",
        zeroToHundred: "9.7 s", topSpeed: "112 mph", fuelEconomy: "4.7 L/100km", range: "800 km",
        length: "4600 mm", width: "1800 mm", height: "1700 mm", wheelbase: "2670 mm",
        trackFront: "1560 mm", trackRear: "1570 mm", groundClearance: "200 mm", curbWeight: "1500 kg",
        gvwr: "2000 kg", towingCapacity: "1500 kg", payloadCapacity: "500 kg",
        frontSuspension: "MacPherson", rearSuspension: "Torsion beam", steeringType: "Rack-and-pinion",
        turningCircle: "11.2 m", brakeType: "Disc/disc", wheelSize: "17\"", tireSize: "215/65R17",
        headroomFront: "990 mm", headroomRear: "960 mm", legroomFront: "1060 mm", legroomRear: "960 mm",
        shoulderFront: "1420 mm", shoulderRear: "1370 mm", hipFront: "1360 mm", hipRear: "1310 mm",
        passengerVolume: "3.0 m³", seatingCapacity: 5, cargoVolume: "702 L", cargoFolded: "1600 L",
        trunkOpeningWidth: "1050 mm", trunkOpeningHeight: "800 mm", liftoverHeight: "700 mm",
        fuelTank: "50 L", estimatedRange: "800 km", crashTestRatings: "5 stars", standardSafety: "6 airbags, AEB",
        availableADAS: "Lane Keep, Adaptive Cruise", screenSize: "10\"", appleCarPlay: "Yes", androidAuto: "Yes",
        audioSystem: "6 speakers", usbPorts: "4", num12VOutlets: "2", wirelessCharging: "Optional",
        seatMaterial: "Cloth", powerSeats: "N/A", heatedSeats: "Front", ventilatedSeats: "N/A",
        dualZoneClimate: "Yes", panoramicSunroof: "Optional", keylessEntry: "Yes", handsFreeLiftgate: "Optional",
        basePrice: "21 990 €", img: "https://www.dacia.sk/content/dam/dacia/sk/models/bigster/bigster-hybrid.jpg",
        buyingLink: "https://www.dacia.sk/bigster"
    },
    {
        make: "Tesla", model: "Model Y", trim: "Long Range AWD", year: 2022, bodyStyle: "SUV", driveType: "AWD",
        engineType: "Electric", displacement: "N/A", cylinders: "N/A", valvetrain: "N/A", aspiration: "N/A",
        horsepower: "384 hp", torque: "376 lb-ft", redline: "N/A", fuelType: "EV", batteryCapacity: "75 kWh",
        electricMotorPower: "346 kW", combinedSystemPower: "346 kW", transmission: "Single-speed",
        zeroToHundred: "5.0 s", topSpeed: "135 mph", fuelEconomy: "16.8 kWh/100km", range: "514 km",
        length: "4750 mm", width: "1921 mm", height: "1624 mm", wheelbase: "2890 mm",
        trackFront: "1637 mm", trackRear: "1624 mm", groundClearance: "167 mm", curbWeight: "2003 kg",
        gvwr: "2549 kg", towingCapacity: "1600 kg", payloadCapacity: "546 kg",
        frontSuspension: "Double wishbone", rearSuspension: "Multi-link", steeringType: "Rack-and-pinion",
        turningCircle: "12.1 m", brakeType: "Disc/disc", wheelSize: "19\"", tireSize: "255/45R19",
        headroomFront: "1041 mm", headroomRear: "1003 mm", legroomFront: "1060 mm", legroomRear: "980 mm",
        shoulderFront: "1420 mm", shoulderRear: "1330 mm", hipFront: "1360 mm", hipRear: "1300 mm",
        passengerVolume: "3.1 m³", seatingCapacity: 5, cargoVolume: "854 L", cargoFolded: "2047 L",
        trunkOpeningWidth: "1100 mm", trunkOpeningHeight: "850 mm", liftoverHeight: "700 mm",
        fuelTank: "N/A", estimatedRange: "514 km", crashTestRatings: "5 stars", standardSafety: "8 airbags, AEB",
        availableADAS: "Autopilot, FSD", screenSize: "15\"", appleCarPlay: "No", androidAuto: "No",
        audioSystem: "14 speakers", usbPorts: "2", num12VOutlets: "1", wirelessCharging: "Yes",
        seatMaterial: "Vegan leather", powerSeats: "Front", heatedSeats: "All", ventilatedSeats: "Front",
        dualZoneClimate: "Yes", panoramicSunroof: "Glass roof", keylessEntry: "Yes", handsFreeLiftgate: "Yes",
        basePrice: "33 990 €", img: "https://digitalassets.tesla.com/tesla-contents/image/upload/h_1800,w_2880,c_fit,f_auto,q_auto:best/Model-Y-Hero-Desktop",
        buyingLink: "https://www.tesla.com/sk_sk/modely/model-y"
    },
    {
        make: "Hyundai", model: "Ioniq 5", trim: "Premium", year: 2025, bodyStyle: "Crossover SUV", driveType: "RWD",
        engineType: "Electric", displacement: "N/A", cylinders: "N/A", valvetrain: "N/A", aspiration: "N/A",
        horsepower: "215 hp", torque: "350 Nm", redline: "N/A", fuelType: "EV", batteryCapacity: "77.4 kWh",
        electricMotorPower: "160 kW", combinedSystemPower: "160 kW", transmission: "Single-speed",
        zeroToHundred: "7.4 s", topSpeed: "185 km/h", fuelEconomy: "17.0 kWh/100km", range: "507 km",
        length: "4635 mm", width: "1890 mm", height: "1605 mm", wheelbase: "3000 mm",
        trackFront: "1634 mm", trackRear: "1638 mm", groundClearance: "160 mm", curbWeight: "2140 kg",
        gvwr: "2560 kg", towingCapacity: "1600 kg", payloadCapacity: "420 kg",
        frontSuspension: "MacPherson", rearSuspension: "Multi-link", steeringType: "Rack-and-pinion",
        turningCircle: "11.7 m", brakeType: "Disc/disc", wheelSize: "19\"", tireSize: "235/50R19",
        headroomFront: "1030 mm", headroomRear: "1000 mm", legroomFront: "1080 mm", legroomRear: "1000 mm",
        shoulderFront: "1460 mm", shoulderRear: "1440 mm", hipFront: "1380 mm", hipRear: "1330 mm",
        passengerVolume: "3.1 m³", seatingCapacity: 5, cargoVolume: "527 L", cargoFolded: "1587 L",
        trunkOpeningWidth: "1050 mm", trunkOpeningHeight: "800 mm", liftoverHeight: "700 mm",
        fuelTank: "N/A", estimatedRange: "507 km", crashTestRatings: "5 stars", standardSafety: "7 airbags, AEB",
        availableADAS: "Highway Drive Assist", screenSize: "12.3\"", appleCarPlay: "Yes", androidAuto: "Yes",
        audioSystem: "8 speakers", usbPorts: "4", num12VOutlets: "2", wirelessCharging: "Yes",
        seatMaterial: "Leatherette", powerSeats: "Driver/Passenger", heatedSeats: "Front/Rear", ventilatedSeats: "Front",
        dualZoneClimate: "Yes", panoramicSunroof: "Optional", keylessEntry: "Yes", handsFreeLiftgate: "Yes",
        basePrice: "43 390 €", img: "https://www.hyundai.sk/wp-content/uploads/2025/01/ioniq5.jpg",
        buyingLink: "https://www.hyundai.sk/ioniq-5"
    },
    {
        make: "Hyundai", model: "Tucson Hybrid", trim: "Premium", year: 2025, bodyStyle: "Compact SUV", driveType: "FWD",
        engineType: "1.6L + Electric", displacement: "1.6L", cylinders: 4, valvetrain: "DOHC", aspiration: "Turbo",
        horsepower: "231 hp", torque: "265 lb-ft", redline: "N/A", fuelType: "Hybrid", batteryCapacity: "1.49 kWh",
        electricMotorPower: "44 hp", combinedSystemPower: "231 hp", transmission: "6-speed auto",
        zeroToHundred: "8.3 s", topSpeed: "124 mph", fuelEconomy: "5.6 L/100km", range: "800 km",
        length: "4630 mm", width: "1865 mm", height: "1665 mm", wheelbase: "2755 mm",
        trackFront: "1620 mm", trackRear: "1627 mm", groundClearance: "181 mm", curbWeight: "1725 kg",
        gvwr: "2210 kg", towingCapacity: "1650 kg", payloadCapacity: "485 kg",
        frontSuspension: "MacPherson", rearSuspension: "Multi-link", steeringType: "Rack-and-pinion",
        turningCircle: "11.8 m", brakeType: "Disc/disc", wheelSize: "18\"", tireSize: "235/60R18",
        headroomFront: "1010 mm", headroomRear: "990 mm", legroomFront: "1050 mm", legroomRear: "990 mm",
        shoulderFront: "1480 mm", shoulderRear: "1430 mm", hipFront: "1400 mm", hipRear: "1350 mm",
        passengerVolume: "3.1 m³", seatingCapacity: 5, cargoVolume: "620 L", cargoFolded: "1799 L",
        trunkOpeningWidth: "1020 mm", trunkOpeningHeight: "800 mm", liftoverHeight: "750 mm",
        fuelTank: "52 L", estimatedRange: "800 km", crashTestRatings: "5 stars", standardSafety: "6 airbags, AEB",
        availableADAS: "Highway Drive Assist", screenSize: "10.25\"", appleCarPlay: "Yes", androidAuto: "Yes",
        audioSystem: "6 speakers", usbPorts: "4", num12VOutlets: "2", wirelessCharging: "Yes",
        seatMaterial: "Cloth", powerSeats: "Driver", heatedSeats: "Front/Rear", ventilatedSeats: "N/A",
        dualZoneClimate: "Yes", panoramicSunroof: "Optional", keylessEntry: "Yes", handsFreeLiftgate: "Yes",
        basePrice: "37 500 €", img: "https://www.hyundai.sk/wp-content/uploads/2025/02/tucson-hybrid.jpg",
        buyingLink: "https://www.hyundai.sk/tucson-hybrid"
    },
{
    make: "Mazda",
    model: "CX-5",
    trim: "Skyactiv-G",
    year: 2020,
    bodyStyle: "Compact SUV",
    driveType: "FWD",

    engineType: "Inline-4",
    displacement: "2.0 L",
    cylinders: "4",
    valvetrain: "DOHC",
    aspiration: "Naturally Aspirated",

    horsepower: "165 hp",
    torque: "213 Nm",
    redline: "6500 rpm",
    fuelType: "Petrol",

    batteryCapacity: "N/A",
    electricMotorPower: "N/A",
    combinedSystemPower: "165 hp",

    transmission: "6-speed Automatic",

    zeroToHundred: "10.3 s",
    topSpeed: "201 km/h",
    fuelEconomy: "6.9 L/100 km",
    range: "820 km",

    length: "4550 mm",
    width: "1840 mm",
    height: "1680 mm",
    wheelbase: "2700 mm",

    trackFront: "1595 mm",
    trackRear: "1595 mm",
    groundClearance: "192 mm",

    curbWeight: "1515 kg",
    gvwr: "2060 kg",
    towingCapacity: "1800 kg",
    payloadCapacity: "545 kg",

    frontSuspension: "MacPherson Strut",
    rearSuspension: "Multi-link",
    steeringType: "Electric Power Steering",
    turningCircle: "11.0 m",

    brakeType: "Disc/disc",
    wheelSize: "17\"",
    tireSize: "225/65R17",

    headroomFront: "1020 mm",
    headroomRear: "990 mm",
    legroomFront: "1040 mm",
    legroomRear: "1000 mm",

    shoulderFront: "1450 mm",
    shoulderRear: "1410 mm",
    hipFront: "1380 mm",
    hipRear: "1360 mm",

    passengerVolume: "3.0 m³",
    seatingCapacity: 5,

    cargoVolume: "506 L",
    cargoFolded: "1620 L",

    trunkOpeningWidth: "1100 mm",
    trunkOpeningHeight: "800 mm",
    liftoverHeight: "720 mm",

    fuelTank: "56 L",
    estimatedRange: "820 km",

    crashTestRatings: "5 stars (Euro NCAP)",
    standardSafety: "6 airbags, ABS, ESC, AEB",
    availableADAS: "Adaptive Cruise, Lane Assist, Blind Spot Monitoring",

    screenSize: "7\"",
    appleCarPlay: "Yes",
    androidAuto: "Yes",

    audioSystem: "6 speakers",
    usbPorts: "2",
    num12VOutlets: "2",
    wirelessCharging: "No",

    seatMaterial: "Cloth / Leather (depending on trim)",
    powerSeats: "Driver",
    heatedSeats: "Front",
    ventilatedSeats: "No",

    dualZoneClimate: "Yes",
    panoramicSunroof: "Optional",
    keylessEntry: "Yes",
    handsFreeLiftgate: "Optional",

    basePrice: "≈ 26 000 €",
    img: "https://upload.wikimedia.org/wikipedia/commons/8/8f/2019_Mazda_CX-5.jpg",
    buyingLink: "https://www.mazda.eu"
}

];
